// Manasana v1 content — emotions and poses.
// Instructions and default durations mirror docs/poses.md.
// Durations are defaults; the user can adjust them in the timer.

export const POSES = {
  'legs-up-wall': {
    id: 'legs-up-wall',
    name: 'Legs-Up-the-Wall',
    level: 'B',
    defaultDurationSec: 120,
    perSide: false,
    instructions: [
      'Sit sideways next to a wall, one hip touching it.',
      'Lie back and swing your legs up the wall as you turn to face it.',
      'Scoot your sitting bones close to the wall; rest your arms by your sides, palms up.',
      'Soften your legs, close your eyes, and breathe slowly.',
    ],
    cue: 'A folded blanket under your hips adds support.',
  },
  'childs-pose': {
    id: 'childs-pose',
    name: "Child's Pose",
    level: 'B',
    defaultDurationSec: 60,
    perSide: false,
    instructions: [
      'Kneel with big toes together and knees apart.',
      'Sit your hips back toward your heels.',
      'Walk your hands forward and lower your forehead to the mat.',
      'Let your arms rest forward or alongside your body; breathe into your back.',
    ],
    cue: 'Supported: rest your torso and forehead on a cushion or folded blanket.',
  },
  'reclined-bound-angle': {
    id: 'reclined-bound-angle',
    name: 'Reclined Bound Angle',
    level: 'B',
    defaultDurationSec: 120,
    perSide: false,
    instructions: [
      'Lie on your back, knees bent, feet on the floor.',
      'Bring the soles of your feet together and let your knees fall open.',
      'Rest your arms by your sides, palms up.',
      'Support each outer thigh with a cushion if the stretch feels strong; breathe slowly.',
    ],
  },
  'modified-tree': {
    id: 'modified-tree',
    name: 'Modified Tree Pose',
    level: 'B',
    defaultDurationSec: 30,
    perSide: true,
    instructions: [
      'Stand tall, weight on your left foot.',
      'Rest your right toes on the floor with the heel against your left ankle (kickstand), or place the sole on your calf — never the knee.',
      'Bring your palms together at your chest.',
      'Fix your gaze on one point. Hold, then switch sides.',
    ],
    cue: 'Stand near a wall for support.',
  },
  'seated-twist': {
    id: 'seated-twist',
    name: 'Seated Twist',
    level: 'B',
    defaultDurationSec: 30,
    perSide: true,
    instructions: [
      'Sit cross-legged or on a chair, spine tall.',
      'Inhale and lengthen up through the crown.',
      'Exhale and gently twist right — right hand behind you, left hand on your right knee.',
      'Keep it gentle; gaze past your right shoulder. Hold, then switch sides.',
    ],
  },
  'eagle-arms': {
    id: 'eagle-arms',
    name: 'Eagle Arms',
    level: 'B',
    defaultDurationSec: 30,
    perSide: true,
    instructions: [
      'Sit or stand tall; extend both arms forward.',
      'Cross your right arm under your left, bend the elbows, and wrap the forearms so palms (or backs of hands) meet.',
      'Lift your elbows slightly and reach fingertips up; feel the stretch across your upper back.',
      'Breathe, then unwind and switch the top arm.',
    ],
  },
  mountain: {
    id: 'mountain',
    name: 'Mountain Pose',
    level: 'B',
    defaultDurationSec: 45,
    perSide: false,
    instructions: [
      'Stand with feet hip-width, weight even across both feet.',
      'Lengthen your spine; relax your shoulders down and back.',
      'Let your arms rest by your sides, palms forward.',
      'Breathe steadily and feel grounded through your feet.',
    ],
  },
  'standing-forward-fold': {
    id: 'standing-forward-fold',
    name: 'Standing Forward Fold',
    level: 'B',
    defaultDurationSec: 60,
    perSide: false,
    instructions: [
      'Stand with feet hip-width, a soft bend in your knees.',
      'Hinge from your hips and fold forward, letting your head hang heavy.',
      'Hold opposite elbows and sway gently, or rest your hands on the floor or shins.',
      'Keep knees bent as needed; breathe. To rise, bend your knees and roll up slowly.',
    ],
  },
  'cat-cow': {
    id: 'cat-cow',
    name: 'Cat-Cow',
    level: 'B',
    defaultDurationSec: 60,
    perSide: false,
    instructions: [
      'Come to hands and knees, wrists under shoulders, knees under hips.',
      'Inhale: drop your belly, lift your chest and tailbone (Cow).',
      'Exhale: round your spine, tuck your chin and tailbone (Cat).',
      'Flow slowly with your breath for several rounds.',
    ],
  },
  cobra: {
    id: 'cobra',
    name: 'Cobra Pose',
    level: 'B',
    defaultDurationSec: 30,
    perSide: false,
    instructions: [
      'Lie face down, legs extended, hands under your shoulders, elbows drawn in.',
      'Press the tops of your feet and your pelvis into the floor.',
      'Inhale and gently lift your chest, using your back more than your hands — keep a small, comfortable curve.',
      'Relax your shoulders; lower on an exhale.',
    ],
    cue: 'Keep it low and easy; never force the lift.',
  },
  bridge: {
    id: 'bridge',
    name: 'Bridge Pose',
    level: 'B–I',
    defaultDurationSec: 45,
    perSide: false,
    instructions: [
      'Lie on your back, knees bent, feet hip-width and close to your hips.',
      'Press into your feet and lift your hips toward the ceiling.',
      'Keep your knees over your ankles; clasp your hands under your back or leave your arms flat.',
      'Breathe; lower slowly, one vertebra at a time.',
    ],
  },
  'warrior-2': {
    id: 'warrior-2',
    name: 'Warrior II',
    level: 'B–I',
    defaultDurationSec: 30,
    perSide: true,
    instructions: [
      'Step your feet wide; turn your right foot out 90°, left toes slightly in.',
      'Bend your right knee toward 90°, tracking over the ankle.',
      'Extend your arms to shoulder height, gaze over your right hand.',
      'Keep your torso upright. Hold, then switch sides.',
    ],
  },
  tree: {
    id: 'tree',
    name: 'Tree Pose',
    level: 'B–I',
    defaultDurationSec: 30,
    perSide: true,
    instructions: [
      'Stand tall, weight on your left foot.',
      'Place your right sole on your inner left calf or thigh (avoid the knee).',
      'Bring your palms together at your chest, or reach your arms overhead.',
      'Gaze at a fixed point. Hold, then switch sides.',
    ],
  },
  'seated-forward-fold': {
    id: 'seated-forward-fold',
    name: 'Seated Forward Fold',
    level: 'B',
    defaultDurationSec: 60,
    perSide: false,
    instructions: [
      'Sit with legs extended straight ahead — a folded blanket under your hips helps.',
      'Inhale and lengthen your spine.',
      'Exhale and hinge from your hips, walking your hands toward your feet.',
      'Keep a soft bend in the knees; let your head relax. Breathe.',
    ],
  },
  'low-lunge': {
    id: 'low-lunge',
    name: 'Low Lunge',
    level: 'B',
    defaultDurationSec: 45,
    perSide: true,
    instructions: [
      'From hands and knees, step your right foot forward between your hands.',
      'Lower your left knee to the floor and slide it back until you feel a comfortable hip stretch.',
      'Rise onto your fingertips, or lift your torso with hands on your right thigh.',
      'Keep your front knee over your ankle. Hold, then switch sides.',
    ],
    cue: 'Cushion the back knee with a blanket.',
  },
  sphinx: {
    id: 'sphinx',
    name: 'Sphinx Pose',
    level: 'B',
    defaultDurationSec: 45,
    perSide: false,
    instructions: [
      'Lie face down, legs extended behind you.',
      'Place your forearms on the floor, elbows under your shoulders.',
      'Gently press down and lengthen your chest forward and up.',
      'Relax your shoulders and glutes; breathe softly.',
    ],
  },
  'cow-face-arms': {
    id: 'cow-face-arms',
    name: 'Cow Face Arms',
    level: 'B',
    defaultDurationSec: 30,
    perSide: true,
    instructions: [
      'Sit or stand tall. Reach your right arm up, bend the elbow, and let the hand fall behind your neck.',
      'Bring your left arm behind your back, elbow bent, hand reaching up.',
      'Clasp your fingers if they meet, or hold a strap (or your shirt) between them.',
      'Keep your chest open. Hold, then switch sides.',
    ],
  },
  chair: {
    id: 'chair',
    name: 'Chair Pose',
    level: 'B–I',
    defaultDurationSec: 30,
    perSide: false,
    instructions: [
      'Stand with feet together or hip-width.',
      'Bend your knees and sit your hips back, as if lowering into a chair.',
      'Raise your arms alongside your ears, palms facing each other.',
      'Keep your weight in your heels and your chest lifted. Breathe.',
    ],
  },
  'upward-salute': {
    id: 'upward-salute',
    name: 'Upward Salute',
    level: 'B',
    defaultDurationSec: 30,
    perSide: false,
    instructions: [
      'Stand tall in Mountain Pose.',
      'Inhale and sweep both arms out and up overhead.',
      'Reach your fingertips up, palms facing or together; lift your gaze slightly if comfortable.',
      'Relax your shoulders away from your ears. Breathe.',
    ],
  },
};

export const EMOTIONS = [
  { id: 'exhausted', label: 'Exhausted', sense: 'depleted', emoji: '🥱', poseIds: ['legs-up-wall', 'childs-pose', 'reclined-bound-angle'] },
  { id: 'confused', label: 'Confused', sense: 'mental fog', emoji: '🤔', poseIds: ['modified-tree', 'seated-twist', 'eagle-arms'] },
  { id: 'afraid', label: 'Afraid', sense: 'fear / anxiety', emoji: '😨', poseIds: ['mountain', 'standing-forward-fold', 'cat-cow'] },
  { id: 'hopeless', label: 'Hopeless', sense: 'despair', emoji: '🌧️', poseIds: ['cobra', 'bridge', 'warrior-2'] },
  { id: 'restless', label: 'Restless', sense: "can't settle", emoji: '🌀', poseIds: ['tree', 'warrior-2', 'seated-forward-fold'] },
  { id: 'overwhelmed', label: 'Overwhelmed', sense: 'too much', emoji: '🌊', poseIds: ['childs-pose', 'standing-forward-fold', 'legs-up-wall'] },
  { id: 'numb', label: 'Numb', sense: 'flat', emoji: '😶', poseIds: ['cat-cow', 'low-lunge', 'bridge'] },
  { id: 'lonely', label: 'Lonely', sense: 'disconnected', emoji: '🌙', poseIds: ['sphinx', 'reclined-bound-angle', 'cow-face-arms'] },
  { id: 'unmotivated', label: 'Unmotivated / Stuck', sense: "can't get going", emoji: '🪫', poseIds: ['chair', 'low-lunge', 'upward-salute'] },
  { id: 'ashamed', label: 'Ashamed', sense: 'guilt', emoji: '🙈', poseIds: ['childs-pose', 'cobra', 'reclined-bound-angle'] },
];

export const SAFETY_NOTE =
  'Move gently and never into pain. Skip or modify anything that doesn’t feel right. Manasana is a wellness aid, not medical advice.';
